version = 0.1
[default.deploy.parameters]
stack_name = "ChatGPTBot"
resolve_s3 = true
s3_prefix = "ChatGPTBot"
region = "ap-northeast-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
